nodejs-studio
Syrian-Open-Source/nodejs-studio pull request #1
Opened 2022-02-17 07:44 UTC by MhdTa

2022-02-17 19:13 UTC, karam-mustafa commented
Hi muhammad, I suggest to put your linked in profile, instead of gmail email

2022-02-17 19:16 UTC, karam-mustafa requested changes

2022-02-17 19:16 UTC, karam-mustafa commented on package.json
> +    "description": "",
Add description here please

2022-02-17 19:16 UTC, karam-mustafa commented on package.json
> +    "author": "Yogesh Chavan <myogeshchavan97@gmail.com>",
update author details and license

2022-02-17 20:19 UTC, karam-mustafa commented
And you should specify the version for this PR and the description

2022-02-20 14:10 UTC, MhdTa commented
done (:
Thank you, Mr.Karam

2022-02-21 22:36 UTC, merged